### ISSUE TITLE
Put link to HTML site on repo "link"

### ISSUE THREAD

**Issue by athowes** [elizavetasemenova/prob-epi#26]
I suggest linking to https://elizavetasemenova.github.io/prob-epi on the repo's site link option (to the right).

**Comment by elizavetasemenova** [comment]
where is it, you mean?

**Comment by athowes** [comment]
Should be here:

<img width="351" alt="image" src="https://github.com/elizavetasemenova/prob-epi/assets/29818116/5b27f16e-db1c-4fa5-90da-02ffe9b31c57">

**Comment by elizavetasemenova** [comment]
got it! great suggestion, thanks
