### ISSUE TITLE
Task 15, in 05_Bayesian_inference.ipynb

### ISSUE THREAD

**Issue by Y-Aladdin** [elizavetasemenova/prob-epi#39]
in the "Derive the maximum aposteriori estimate (MAP) for parameter **p**, using a beta prior" .

it should be "Derive the maximum aposteriori estimate (MAP) for parameter **theta**, using a beta prior"

it is theta not p .

**Comment by elizavetasemenova** [comment]
please make a pull request

**Comment by Y-Aladdin** [comment]
done
