### ISSUE TITLE
Updating wget link in Bayesian workflow Notebook

### ISSUE THREAD

**Issue by AhMedDa1** [elizavetasemenova/prob-epi#40]
Hello, 

If you please change the link of getting data in Bayesian workflow notebook to this one, cause in your way you get html content, and you should use the raw to correctly import it in csv.

!wget -O Howell1.csv https://raw.githubusercontent.com/elizavetasemenova/prob-epi/main/data/Howell1.csv

**Comment by elizavetasemenova** [comment]
do you want to make a pull request to correct it? Please keep that line commented as it is now.
